<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240607094809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE banner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, style_id INT DEFAULT NULL, media_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6F9DB8E7BACD6074 ON banner (style_id)');
        $this->addSql('CREATE INDEX IDX_6F9DB8E7EA9FDD75 ON banner (media_id)');
        $this->addSql('ALTER TABLE banner ADD CONSTRAINT FK_6F9DB8E7BACD6074 FOREIGN KEY (style_id) REFERENCES style_sheet (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE banner ADD CONSTRAINT FK_6F9DB8E7EA9FDD75 FOREIGN KEY (media_id) REFERENCES media_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE banner DROP CONSTRAINT FK_6F9DB8E7BACD6074');
        $this->addSql('ALTER TABLE banner DROP CONSTRAINT FK_6F9DB8E7EA9FDD75');
        $this->addSql('DROP TABLE banner');
    }
}
